// Auto-generated by scripts/write-build-info.mjs
export const BUILD_INFO = {
  appVersion: "0.9.4",
  packageVersion: "0.9.4",
  displayVersion: "0.9.4-dev-c5c9716-0007",
  buildTime: "2026-05-15T00:07:04.955Z",
  runtimeMode: "guided-runtime-refactor",
  gitHash: "c5c9716",
  generated: true,
}
